# Generated by Django 5.0.2 on 2024-03-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_from', models.TimeField()),
                ('parking_to', models.TimeField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.parking')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechicle_type', models.CharField(max_length=255)),
                ('price_hour', models.CharField(max_length=255)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('contact', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parking',
            name='user',
            field=models.ManyToManyField(to='models.users'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ManyToManyField(related_name='user', to='models.users'),
        ),
    ]
