# Generated by Django 5.0.2 on 2024-03-03 08:05

import django.db.models.deletion
import djangoProject.mangaers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', djangoProject.mangaers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.role'),
        ),
    ]
