# Generated by Django 3.1.3 on 2024-02-25 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='CITIZENSHIP_NO',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Phone_No',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 3, 18, 37, 747264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 3, 18, 37, 746251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 3, 18, 37, 749171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 3, 18, 37, 747264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Registeration_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 3, 18, 37, 747264, tzinfo=utc)),
        ),
    ]
